//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.Data.Idiomas {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingChallenge.Data.Idiomas.es", typeof(es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circulo.
        /// </summary>
        internal static string CIRCLE {
            get {
                return ResourceManager.GetString("CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Circulos.
        /// </summary>
        internal static string CIRCLE_PL {
            get {
                return ResourceManager.GetString("CIRCLE-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista no contiene formas geometricas.
        /// </summary>
        internal static string EMPTY {
            get {
                return ResourceManager.GetString("EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}{1} | Area: {2} | Perimetro {3} .
        /// </summary>
        internal static string INFO {
            get {
                return ResourceManager.GetString("INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de Formas Geometricas.
        /// </summary>
        internal static string NOT_EMPTY {
            get {
                return ResourceManager.GetString("NOT-EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectangulo.
        /// </summary>
        internal static string RECTANGLE {
            get {
                return ResourceManager.GetString("RECTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rectangulos.
        /// </summary>
        internal static string RECTANGLE_PL {
            get {
                return ResourceManager.GetString("RECTANGLE-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrado.
        /// </summary>
        internal static string SQUARE {
            get {
                return ResourceManager.GetString("SQUARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuadrados.
        /// </summary>
        internal static string SQUARE_PL {
            get {
                return ResourceManager.GetString("SQUARE-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total:.
        /// </summary>
        internal static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Area Total: {0}.
        /// </summary>
        internal static string TOTAL_AREA {
            get {
                return ResourceManager.GetString("TOTAL-AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perimetro Total: {0}.
        /// </summary>
        internal static string TOTAL_PERIMETER {
            get {
                return ResourceManager.GetString("TOTAL-PERIMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay {0} Forma Geometrica.
        /// </summary>
        internal static string TOTAL_SHAPES {
            get {
                return ResourceManager.GetString("TOTAL-SHAPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay {0} Formas Geometricas.
        /// </summary>
        internal static string TOTAL_SHAPES_PL {
            get {
                return ResourceManager.GetString("TOTAL-SHAPES-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapezoide.
        /// </summary>
        internal static string TRAPEZOID {
            get {
                return ResourceManager.GetString("TRAPEZOID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trapezoides.
        /// </summary>
        internal static string TRAPEZOID_PL {
            get {
                return ResourceManager.GetString("TRAPEZOID-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulo.
        /// </summary>
        internal static string TRIANGLE {
            get {
                return ResourceManager.GetString("TRIANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triangulos.
        /// </summary>
        internal static string TRIANGLE_PL {
            get {
                return ResourceManager.GetString("TRIANGLE-PL", resourceCulture);
            }
        }
    }
}
